"""
CadX Studio — Post-Processor for ACE JT-40 (Fanuc 0i-MF compatible)
Converts CLData to verified G-code for the ACE Micromatic JT-40 VMC.

Machine specs (ACE JT-40):
  • Controller : Fanuc 0i-MF
  • Spindle    : BT40, 6000 RPM max, 7.5 kW
  • Travel     : X=1000 Y=500 Z=500 mm
  • Tool changer: 24 ATC positions
  • Coolant    : Flood + mist
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Optional

from cam_engine import CLData, CLPoint, Operation, DrillCycle


# ── Machine limits (ACE JT-40) ─────────────────────────────────────

MACHINE = {
    "name":      "ACE JT-40",
    "ctrl":      "Fanuc 0i-MF",
    "x_min":     0.0, "x_max":  1000.0,
    "y_min":     0.0, "y_max":   500.0,
    "z_min":  -500.0, "z_max":     0.0,
    "rpm_max":  6000,
    "feed_max": 5000,   # mm/min
    "rapid_rate": 15000,
}

COORD_PRECISION = 4   # decimal places for X Y Z
FEED_PRECISION  = 1   # decimal places for F


# ── Header / footer blocks ─────────────────────────────────────────

def _safety_block() -> List[str]:
    return [
        "G21",        # Metric mode
        "G40",        # Cancel tool radius compensation
        "G49",        # Cancel tool length offset
        "G80",        # Cancel fixed cycle
        "G90",        # Absolute mode
        "G94",        # Feed per minute
        "G17",        # XY plane selection
    ]


def _program_header(cl: CLData, prog_no: int) -> List[str]:
    lines = []
    lines.append(f"O{prog_no:04d}")
    lines.append(f"({cl.part_name.upper()})")
    lines.append(f"(MATERIAL: {cl.material.upper()})")
    lines.append(f"(GENERATED BY CADX STUDIO)")
    lines.append(f"(MACHINE: {MACHINE['name']} | CTRL: {MACHINE['ctrl']})")
    lines.append(
        f"(STOCK: X{cl.bounding_box['xsize']:.2f} "
        f"Y{cl.bounding_box['ysize']:.2f} "
        f"Z{cl.bounding_box['zsize']:.2f})"
    )
    lines.append(f"(PART ZERO: WCS G54 — STOCK TOP CENTRE)")
    lines.append("%")
    lines.append("N1 " + " ".join(_safety_block()))
    lines.append("N2 G54")   # Work coordinate system
    lines.append("N3 G28 U0. W0.")   # Machine home (X, Z axes safe move)
    return lines


def _tool_call(op: Operation, seq: list) -> List[str]:
    """Generate tool change + spindle start block."""
    n = seq[0]; seq[0] += 1
    lines = []
    lines.append(f"(------- {op.name.upper()} -------)")
    lines.append(f"({op.comment})")
    lines.append(f"N{n} T{op.tool_no:02d}T{op.tool_no+1:02d}")      # Tool select + pre-index next
    n = seq[0]; seq[0] += 1
    lines.append(f"N{n} M06")                                          # Tool change
    n = seq[0]; seq[0] += 1
    rpm = min(op.cutting.spindle_rpm, MACHINE["rpm_max"])
    lines.append(f"N{n} G97 S{rpm} M03")                              # Spindle CW, constant RPM
    n = seq[0]; seq[0] += 1
    lines.append(f"N{n} G43 H{op.tool_no:02d}")                       # Tool length offset
    n = seq[0]; seq[0] += 1
    lines.append(f"N{n} M08")                                          # Coolant ON (flood)
    return lines


def _fmt_coord(val: float) -> str:
    return f"{val:.{COORD_PRECISION}f}"


def _fmt_feed(val: float) -> str:
    clamped = min(val, MACHINE["feed_max"])
    return f"{clamped:.{FEED_PRECISION}f}"


def _validate_coord(x: float, y: float, z: float) -> Optional[str]:
    """Return a warning string if coordinates exceed machine travel."""
    warnings = []
    if not (MACHINE["x_min"] <= x <= MACHINE["x_max"]):
        warnings.append(f"X{x:.3f} out of travel [{MACHINE['x_min']},{MACHINE['x_max']}]")
    if not (MACHINE["y_min"] <= y <= MACHINE["y_max"]):
        warnings.append(f"Y{y:.3f} out of travel [{MACHINE['y_min']},{MACHINE['y_max']}]")
    if not (MACHINE["z_min"] <= z <= MACHINE["z_max"]):
        warnings.append(f"Z{z:.3f} out of travel [{MACHINE['z_min']},{MACHINE['z_max']}]")
    return "; ".join(warnings) if warnings else None


# ── CL → G-code converters ─────────────────────────────────────────

def _cl_points_to_gcode(
    points: List[CLPoint],
    op:     Operation,
    seq:    list,               # mutable [seq_no]
    post_warnings: List[str],
) -> List[str]:
    lines    = []
    last_f   = -1.0
    feed_cut = min(op.cutting.feed_mmmin,   MACHINE["feed_max"])
    feed_plu = min(op.cutting.plunge_mmmin, MACHINE["feed_max"])
    prev_xy  = None

    for pt in points:
        n = seq[0]; seq[0] += 1
        warn = _validate_coord(pt.x, pt.y, pt.z)
        if warn:
            post_warnings.append(f"N{n}: {warn}")

        x = _fmt_coord(pt.x)
        y = _fmt_coord(pt.y)
        z = _fmt_coord(pt.z)

        # Skip zero-length moves
        if prev_xy and abs(pt.x - prev_xy[0]) < 1e-5 and abs(pt.y - prev_xy[1]) < 1e-5:
            if not pt.rapid:
                prev_xy = (pt.x, pt.y)
                continue

        if pt.rapid:
            lines.append(f"N{n} G00 X{x} Y{y} Z{z}")
        elif pt.plunge:
            f = feed_plu
            feed_str = f" F{_fmt_feed(f)}" if abs(f - last_f) > 0.1 else ""
            last_f   = f
            lines.append(f"N{n} G01 X{x} Y{y} Z{z}{feed_str}")
        elif pt.arc:
            arc = pt.arc
            g   = "G02" if arc["type"] == "CW" else "G03"
            i   = _fmt_coord(arc["cx"] - pt.x)
            j   = _fmt_coord(arc["cy"] - pt.y)
            f   = feed_cut
            feed_str = f" F{_fmt_feed(f)}" if abs(f - last_f) > 0.1 else ""
            last_f   = f
            lines.append(f"N{n} {g} X{x} Y{y} Z{z} I{i} J{j}{feed_str}")
        else:
            f = feed_cut
            feed_str = f" F{_fmt_feed(f)}" if abs(f - last_f) > 0.1 else ""
            last_f   = f
            lines.append(f"N{n} G01 X{x} Y{y} Z{z}{feed_str}")

        prev_xy = (pt.x, pt.y)

    return lines


def _drill_cycles_to_gcode(
    drills:   List[DrillCycle],
    op:       Operation,
    seq:      list,
    post_warnings: List[str],
) -> List[str]:
    """Generate G81 (non-peck) or G83 (peck) drilling cycles."""
    lines = []
    feed  = min(op.cutting.feed_mmmin, MACHINE["feed_max"])
    n     = seq[0]; seq[0] += 1

    # Set rapid to first position
    d0 = drills[0]
    lines.append(f"N{n} G00 X{_fmt_coord(d0.x)} Y{_fmt_coord(d0.y)} Z{_fmt_coord(d0.z_top)}")

    # Activate fixed cycle
    n = seq[0]; seq[0] += 1
    if drills[0].peck:
        q = _fmt_coord(drills[0].peck_dep)
        lines.append(
            f"N{n} G83 X{_fmt_coord(d0.x)} Y{_fmt_coord(d0.y)} "
            f"Z{_fmt_coord(d0.z_depth)} R{_fmt_coord(d0.z_top)} Q{q} F{_fmt_feed(feed)}"
        )
    else:
        lines.append(
            f"N{n} G81 X{_fmt_coord(d0.x)} Y{_fmt_coord(d0.y)} "
            f"Z{_fmt_coord(d0.z_depth)} R{_fmt_coord(d0.z_top)} F{_fmt_feed(feed)}"
        )

    # Repeat cycle for remaining positions
    for drill in drills[1:]:
        warn = _validate_coord(drill.x, drill.y, drill.z_depth)
        if warn:
            post_warnings.append(warn)
        n = seq[0]; seq[0] += 1
        lines.append(f"N{n} X{_fmt_coord(drill.x)} Y{_fmt_coord(drill.y)}")

    # Cancel fixed cycle
    n = seq[0]; seq[0] += 1
    lines.append(f"N{n} G80")
    return lines


def _retract_home(seq: list) -> List[str]:
    n = seq[0]; seq[0] += 1
    return [f"N{n} G28 G91 Z0.", f"N{seq[0]} G28 X0. Y0."]


def _program_footer(seq: list) -> List[str]:
    n = seq[0]; seq[0] += 1
    return [
        f"N{n} M05",     # Spindle OFF
        f"N{n+1} M09",   # Coolant OFF
        f"N{n+2} M30",   # Program end + rewind
        "%",
    ]


# ── Main post-processor ────────────────────────────────────────────

def post_process(cl: CLData, prog_no: int = 1) -> tuple[str, List[str]]:
    """
    Convert CLData → Fanuc 0i-MF G-code string.
    Returns (gcode_string, warnings_list).
    """
    seq           = [10]   # sequence counter (mutable list for pass-by-ref)
    post_warnings: List[str] = []
    lines         = []

    # Header
    lines += _program_header(cl, prog_no)

    for op in cl.operations:
        # Tool call
        lines += _tool_call(op, seq)

        # Rapid to safe Z before any lateral move
        n = seq[0]; seq[0] += 1
        lines.append(f"N{n} G00 Z{_fmt_coord(cl.rapid_z)}")

        if op.op_type in ("rough", "finish") and op.cl_points:
            lines += _cl_points_to_gcode(op.cl_points, op, seq, post_warnings)

        elif op.op_type == "drill" and op.drills:
            lines += _drill_cycles_to_gcode(op.drills, op, seq, post_warnings)

        else:
            n = seq[0]; seq[0] += 1
            lines.append(f"N{n} (NO TOOLPATH DATA FOR {op.name})")

        # Retract after each operation
        lines += _retract_home(seq)

    # Footer
    lines += _program_footer(seq)

    # Validate line count (Fanuc 0i-MF: max 9999 sequence numbers)
    if seq[0] > 9990:
        post_warnings.append(
            f"WARNING: Program has {seq[0]} lines — exceeds Fanuc 0i N9999 limit. "
            "Split into sub-programs (M98/M99)."
        )

    gcode = "\n".join(lines)
    return gcode, post_warnings


# ── Cycle time estimator ───────────────────────────────────────────

def estimate_cycle_time(cl: CLData) -> dict:
    """
    Rough cycle time estimate from CLData.
    Returns dict with per-operation and total minutes.
    """
    RAPID_SPEED = 15000.0   # mm/min ACE JT-40 rapid traverse

    results = {}
    total_min = 0.0

    for op in cl.operations:
        dist_cut   = 0.0
        dist_rapid = 0.0
        prev = None

        for pt in op.cl_points:
            if prev is not None:
                d = math.sqrt(
                    (pt.x - prev.x)**2 +
                    (pt.y - prev.y)**2 +
                    (pt.z - prev.z)**2
                )
                if pt.rapid:
                    dist_rapid += d
                else:
                    dist_cut += d
            prev = pt

        feed    = op.cutting.feed_mmmin
        t_cut   = dist_cut   / max(feed, 1)
        t_rapid = dist_rapid / RAPID_SPEED
        t_drill = sum(
            abs(d.z_depth - d.z_top) / max(op.cutting.plunge_mmmin, 1) * 2
            for d in op.drills
        )
        t_op = t_cut + t_rapid + t_drill

        results[op.name] = round(t_op, 2)
        total_min += t_op

    results["total_min"] = round(total_min, 2)
    results["total_formatted"] = f"{int(total_min)}m {int((total_min % 1) * 60)}s"
    return results